### ISSUE TITLE
Not compatible with `cross-fetch` if timeout is set

### ISSUE THREAD

**Issue by nunofgs** [huturen/http-request-mock#15]
Here's an example codesandbox: https://codesandbox.io/p/sandbox/dreamy-pond-2ucjsu

<img width="560" alt="Screenshot 2023-04-06 at 15 20 28" src="https://user-images.githubusercontent.com/92085/230405976-12a43e91-7a68-4cb5-b436-cf3034c25388.png">

You can see above that the Jest tests are hanging due to a timeout that was not cleared.

There is an interesting interaction here which I will attempt to explain:
1. The `cross-fetch` module uses node-fetch [2.x](https://github.com/lquixada/cross-fetch/blob/24dedb4c8a16a33cb9b4d4682fb731438a6a9e2d/package.json#L69).
2. The `node-fetch@2.x` module supports a `timeout` option which [calls setTimeout](https://github.com/node-fetch/node-fetch/blob/70f592d9d2da959df1cebc2dd2314286a4bcf345/src/index.js#L115) when a socket is emitted.
3. `http-request-mock` emits this socket event [inside a process.nextTick call](https://github.com/huturen/http-request-mock/blob/e5ea96e45a72ac51f59b616443d4520f9e1ead51/src/interceptor/node/client-request.ts#L75).

The above causes the order of events to be switched and `node-fetch` is unable to clear the timeout [when a response arrives](https://github.com/node-fetch/node-fetch/blob/70f592d9d2da959df1cebc2dd2314286a4bcf345/src/index.js#L163).

In fact, the timeout will be set _after_ the response arrives, causing the Jest tests to wait until the timer elapses.

Possible solutions:

* Don't call `process.nextTick` (although I imagine it was added for a reason)
* Wait until `cross-fetch` upgrades to `node-fetch@3`, which does not exhibit this behavior. (the timeout option was removed)

**Comment by huturen** [comment]
hi @nunofgs 

> Don't call process.nextTick (although I imagine it was added for a reason)

As per your solution, the issue has been fixed in version [1.8.15](https://www.npmjs.com/package/http-request-mock/v/1.8.15).

![image](https://user-images.githubusercontent.com/5173298/230604341-fc78fb23-471e-4930-8e62-06f172bb9c7b.png)

The reason for calling "process.nextTick" is to delay sending the connect event in order to better simulate the real environment. However, it seems that removing it here may not cause any issues. Here's the code [commit](https://github.com/huturen/http-request-mock/commit/01710c0821ad13855fc08b43451ef8b8a444e072) for this fix.

**Comment by nunofgs** [comment]
Fantastic! Thanks for the quick turnaround.
