### ISSUE TITLE
Cannot mock same URL multiple times with different status

### ISSUE THREAD

**Issue by aminpaks** [huturen/http-request-mock#19]
Hi folks,

I can't seem to find a way to mock a URL multiple specific times with different statuses. The dynamic response works only for the body, and not status, am I missing something?

**Update:**
[This](https://github.com/huturen/http-request-mock/blob/608905f398c07c4b4b2dda092234813aba514dff/src/interceptor/fetch.ts#L240-L244) is the issue, we only support returning the response, and getting the status from the main options instead of allowing the lazy function returns the status including the body.

**Comment by huturen** [comment]
Hi @aminpaks,

You can set status code in the `response` option by `this.status = xxx`, try the code below:
```js
mocker.mock({ 
  url: 'https://test.api.com/', 
  response(req) {
    if (/200/.test(req.url)) {
      this.status = 200;
      return { code: 0, msg: 'ok' };
    }

    this.status = 404;
    return 'Not Found';
  }
});
```
If the URL contains `200`, the HTTP status code will be returned as 200; otherwise, it will be returned as 404.

![image](https://user-images.githubusercontent.com/5173298/202172984-4e881a92-0587-45d5-8e9f-2c070ab4cba2.png)

**Comment by aminpaks** [comment]
Thanks for the quick response!
